// src/schema-form/display/select-display-field.vue
<template>
  <span v-if="value && options">
    <span v-if="hasVNodeLabels">{{ labels }}</span>
    <span v-else>{{ labels.join('、') }}</span>
  </span>
  <span v-else></span>
</template>

<script setup lang="ts">
import { computed, isVNode } from 'vue';
import { getOptionProperty } from '../utils/utils';

const props = defineProps({
  field: Object,
  value: [String, Number, Array, Object],
  options: Array
});

const valueProperty = computed(() => props.field.props.valueProperty || 'value');
const labelProperty = computed(() => props.field.props.labelProperty || 'label');
const options = computed(() => props.options || props.field.options);

const selected = computed(() => {
  if (!props.value || !options.value) return [];
  
  if (props.field.array) {
    return options.value.filter(it => {
      const val = props.value as Array<any>;
      return val.includes(getOptionProperty(it, valueProperty.value)) || val.includes(it);
    });
  } else {
    return options.value.filter(it => 
      props.value === getOptionProperty(it, valueProperty.value) || 
      props.value === it
    );
  }
});

const labels = computed(() => 
  selected.value.map(it => getOptionProperty(it, labelProperty.value))
);

const hasVNodeLabels = computed(() => 
  labels.value.some(it => isVNode(it))
);
</script>

// src/schema-form/display/select-display-field.tsx
import {resolveOptions} from '../utils/utils';

export default (props) => {
  const {field, value} = props;
  const options = resolveOptions(field);
  const valueProperty = field.props.valueProperty || 'value';

  const labelProperty = field.props.labelProperty || 'label';

  if (value) {
    let selected = [];
    if (field.array) {
      selected = options.filter(it => value.includes(it[valueProperty]) || value.includes(it));
    } else {
      selected = options.filter(it => value === it[valueProperty] || value === it);
    }
    return <span>{selected.map(it => typeof it === 'object' ? it[labelProperty] : it).join('、')}</span>;
  } else {
    return <span/>;
  }
}
