// src/schema-form/display/time-display-field.vue
<template>
  <span v-if="isRangeType && value">
    <span>{{ formatTime(value[0] as any, format) }}</span>
    <span> {{ separator || '~' }} </span>
    <span>{{ formatTime(value[1] as any, format) }}</span>
  </span>
  <span v-else>
    {{ formatTime(value as any, format) }}
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { formatTime } from '../utils/time';

const props = defineProps({
  value: [String, Number, Object, Array, Date],
  definition: Object,
  format: String,
  separator: String
});

const format = computed(() => {
  let fmt = props.format || 'YYYY-MM-DD HH:mm:ss';
  
  if (props.definition.type === 'date') {
    fmt = 'YYYY-MM-DD';
  } else if (props.definition.type === 'month') {
    fmt = 'YYYY-MM';
  } else if (props.definition.type === 'year') {
    fmt = 'YYYY';
  } else if (props.definition.type === 'daterange') {
    fmt = 'YYYY-MM-DD';
  } else if (props.definition.type === 'time') {
    fmt = 'HH:mm:ss';
  }
  
  return fmt;
});

const isRangeType = computed(() => 
  ['daterange', 'timerange'].includes(props.definition.type)
);
</script>

// src/schema-form/display/time-display-field.tsx
import {formatTime} from '../utils/time';

export default (props) => {
  const {value, definition} = props;
  let format = 'YYYY-MM-DD HH:mm:ss';
  if (definition.type === 'date') {
    format = 'YYYY-MM-DD';
  } else if (definition.type === 'month') {
    format = 'YYYY-MM';
  } else if (definition.type === 'year') {
    format = 'YYYY';
  } else if (definition.type === 'daterange') {
    format = 'YYYY-MM-DD';
  } else if (definition.type === 'time') {
    format = 'HH:mm:ss';
  }
  if (['daterange', 'timerange'].includes(definition.type) && value) {
    return (
        <span>
          <span>
            {formatTime(value[0], format)}
          </span>
          <span> - </span>
          <span>
            {formatTime(value[1], format)}
          </span>
        </span>
    );
  }
  return (
      <span>
        {formatTime(value, format)}
      </span>
  );
}
