// src/schema-form/antd/button.tsx
import Component from 'vue-class-component';
import BaseButton from '@/schema-form/common/base-button';

@Component({
  name: 'AntdButton'
})
export default class AntdButton extends BaseButton {
  public render() {
    return <a-button attrs={this.$attrs}
                     html-type="button"
                     onClick={this.onClick}>{this.title}</a-button>;
  }
}

// es/mobile/button.tsx
import {EffectsContext} from 'v-schema-form-types';
import Vue from 'vue';
import Component from 'vue-class-component';
import {Inject, Prop} from 'vue-property-decorator';
import {SchemaFormStore} from '../internal/utils';

@Component({
  name: 'AntdButton'
})
export default class AntdButton extends Vue {
  @Prop()
  public action: (context: EffectsContext, event) => any;
  @Prop()
  public title: string;
  @Inject('store')
  public store: SchemaFormStore;


  public onClick(e) {
    if (this.action) {
      this.action(this.store.context, e);
    }
  }

  public render() {
    return <m-button props={this.$attrs}
                     onClick={this.onClick}>{this.title}</m-button>;
  }
}
